import type { ApiError } from "./envelope";

export const API_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REUSED: "TOKEN_REUSED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  MAILBOX_ADDRESS_ALREADY_EXISTS: "MAILBOX_ADDRESS_ALREADY_EXISTS",
  DOMAIN_NOT_ACTIVE: "DOMAIN_NOT_ACTIVE",
  FOLDER_NAME_CONFLICT: "FOLDER_NAME_CONFLICT",
  FOLDER_IS_SYSTEM: "FOLDER_IS_SYSTEM",
  RULESET_INVALID_REGEX: "RULESET_INVALID_REGEX",
  RULESET_INVALID_DEPENDENCY: "RULESET_INVALID_DEPENDENCY",
  OAUTH_NOT_CONFIGURED: "OAUTH_NOT_CONFIGURED",
  CURSOR_INVALID: "CURSOR_INVALID",
  FULL_RESYNC_REQUIRED: "FULL_RESYNC_REQUIRED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export function apiError(
  code: ApiErrorCode,
  message: string,
  details?: Record<string, unknown>
): ApiError {
  return { error: { code, message, ...(details ? { details } : {}) } };
}
